convenient_delivery/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^admin/', include(admin.site.urls)),
  url(r'^accounts/', include('registration.backends.default.urls')),
  url(r'^/*', include('order_processor.urls', namespace="order_processor")), 
)

order_processor/urls.py
from django.conf.urls import patterns, url

from order_processor import views

urlpatterns = patterns('',
    	url(r'^$', views.index, name='index'),
      url(r'^login/', views.login, name='login'),
      url(r'^logout/', views.logout, name = 'logout'),
      url(r'^signup/', views.signup, name='signup'),
      url(r'^successfulsignup/', views.successfulsignup, name='successfulsignup'),
      url(r'^successfullogin/', views.successfullogin, name='successfullogin'),
      url(r'^driver/', views.driver, name='driver'),
      url(r'^order_details/(?P<order_id>\d+)/$', views.order_details, name = 'order_details'),
      url(r'^new_order/', views.new_order, name = 'new_order'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views 

urlpatterns = patterns('',
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
  url(r'^(?P<pk>\d+)/vote/$', views.vote, name='vote'),
)

order_processor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from decimal import *
# Create your models here.

class City(models.Model):

	city = models.CharField(max_length=255) 
	description = models.CharField(max_length=255) 
	currently_open = models.BooleanField(default=False)

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.city	

class Address(models.Model):
  address_line_1 = models.CharField(max_length=255)
  address_line_2 = models.CharField(max_length=255, blank = True, null = True)
  city = models.CharField(max_length=255)
  state = models.CharField(max_length=255)
  zipcode = models.CharField(max_length=255)

  class Category(models.Model):
    class Meta:
      verbose_name = "Address"

  def __unicode__(self):
    return self.address_line_1

class Profile(models.Model):

  user =	models.OneToOneField(User)
  address = models.ForeignKey(Address, blank = True, null = True)
  phone = models.CharField(max_length=255)

  def __unicode__(self):  # Python 3: def __str__(self):
    return self.user.username

class SaleItem(models.Model):
 
  name = models.CharField(max_length=255)  
  description = models.CharField(max_length=255)
  price = models.DecimalField(max_digits=50, decimal_places=2)
  establishment = models.OneToOneField('Establishment', null = True) #quotes required because model is not defined yet!
  category = models.OneToOneField('ItemCategory', null = True)

  def __unicode__(self):
    display_name = self.establishment.name + " | " + self.name + " | " + str(self.price) 
    return display_name 

class ItemCategory(models.Model):

  name = models.CharField(max_length=255)
  establishment = models.OneToOneField('Establishment', null = True) #quotes required because model is not defined yet!

  def __unicode__(self):  # Python 3: def __str__(self):
    return self.name

class Establishment(models.Model):
  
  city = models.ForeignKey(City, null = True)
  name = models.CharField(max_length=255)
  address = models.OneToOneField(Address, null = True)
  phone = models.CharField(max_length=255)
  
  def __unicode__(self):
    return self.name

class Driver(models.Model):
	# add drivers hours, active or not
 
  user = models.OneToOneField(User)
  city = models.ForeignKey(City)
  currently_active = models.BooleanField(default=False)
  phone = models.CharField(max_length=255)

  def __unicode__(self):  # Python 3: def __str__(self):
    return self.user.username

class Order(models.Model):

  STATUS_CHOICES = (
    ('q', 'In Queue'),
    ('p', 'Pick Up'),
    ('r', 'On Route'),
    ('d', 'Delivered'),
  )
  profile = models.ForeignKey(Profile, null = True)
  items = models.ManyToManyField(SaleItem, null = True) 
  status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='q') 
  city = models.ForeignKey(City)
  driver = models.ForeignKey(Driver)
  date = models.DateTimeField()
  delivered = models.BooleanField(default=False)
  work_required = models.BooleanField(default=False) #This would be true if an order needed to be placed
  establishment = models.ManyToManyField(Establishment)
  
  def _cost(self):
    x = Decimal(0)
    items_list = self.items.all()
    for item in items_list:
      x =  x + item.price
    return x

  cost = property(_cost)
  
  def __unicode__(self):  # Python 3: def __str__(self):
    self_order = models.ForeignKey('self')
    current_city = self.city
    current_username = self.profile.user.username 
    name = "CITY / " + current_city.city + " | " + "USERNAME / " + current_username + " | "  
    for establishment in self.establishment.all():
      name = name + "ESTABLISHMENT / " + establishment.name + " | "
    return name 

order_processor/forms.py
from django import forms
from order_processor.models import *

class CitySelect(forms.Form):
  cities = City.objects.all() 

  attrs = {'class' : 'selectpicker show-menu-arrow', 'data-width' : 'auto'}
  widget = forms.Select(attrs=attrs)


  city = forms.ModelChoiceField(queryset = cities, label='', widget=widget, empty_label = None)

class EstablishmentSelect(forms.Form):
  def __init__(self, *args, **kwargs):
    establishment_list = kwargs.pop('establishment_list')
    super(EstablishmentSelect, self).__init__(*args, **kwargs)
    self.fields['establishment'] = forms.ModelChoiceField(queryset = establishment_list, empty_label = None)

class login(forms.Form):
  username = forms.CharField(max_length = 100, widget = forms.TextInput(attrs={'color': 'black'}))
  password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'selectpicker show-menu-arrow', 'data-width' : 'auto'}))

class signup(forms.Form):
  username = forms.CharField(max_length = 100, widget = forms.TextInput(attrs={'color': 'black'}))
  password = forms.CharField(widget=forms.PasswordInput(attrs={
                                                                'class' : 'selectpicker show-menu-arrow', 
                                                                'data-width' : 'auto'
                                                              }))
  email = forms.EmailField(max_length=254)
  first_name = forms.CharField(max_length = 100, widget = forms.TextInput({}))
  last_name = forms.CharField(max_length = 100, widget = forms.TextInput({}))
  
  def clean_username(self):
    username = self.cleaned_data['username']
    if User.objects.exclude(pk = self.instance.pk).filter(username=username).exists():
      raise forms.ValidationError(u'Username "%s" is already in use.' % username)
    return username 

order_processor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import render
from django.template import RequestContext, loader
from order_processor.models import *
from order_processor import forms
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelChoiceField

def index(request):
  #output = "test output"
  
  city_selector = forms.CitySelect()
  login = forms.login()
  
  
  context = {
              'city_select' : city_selector,
              'login' : login,
            }
  return render(request, 'order_processor/index.html', context)


def new_order(request):
  if request.method == 'POST':
    current_city =  request.POST['city'] 
    establishment_list = Establishment.objects.all().filter(city = current_city)
    
    establishment_selector = forms.EstablishmentSelect(establishment_list = establishment_list)
     
    context = {
              'establishment_selector' : establishment_selector,
              }
    return render(request, 'order_processor/new_order.html', context)
  else:
    return redirect('index')  
  
  

  return render(request, 'order_processor/order.html', context)

def login(request):
  if request.user.is_authenticated():
    first_name = request.user.first_name
    last_name = request.user.last_name
    context = {
                'first_name' : first_name,
                'last_name' : last_name,
              }
    return render(request, 'order_processor/alreadyloggedin.html', context)
  else:
    authenticationForm = AuthenticationForm()
  
    context = {
              'authenticationForm': authenticationForm,
             }
    return render (request, 'order_processor/login.html', context)
 
def logout(request):
  auth_logout(request)
  context = {}
  return render(request, 'order_processor/logout.html', context)
 
def signup(request):
  signup = forms.signup()

  context = {
              'signup' : signup ,
            }
  return render (request, 'order_processor/signup.html', context)

def successfulsignup(request):
  username = request.POST['username']
  password = request.POST['password']
  email = request.POST['email']
  first_name = request.POST['first_name']
  last_name = request.POST['last_name']
  user = User.objects.create_user(username, email, password)
  user_list = User.objects.all() 
  user.last_name = last_name
  user.first_name = first_name
  context = {
              'username':username,
              'email':email,
              'first_name':first_name,
              'last_name':last_name,
            }
  return render(request, 'order_processor/successfulsignup.html', context)

def successfullogin(request):
  username = request.POST['username']
  password = request.POST['password']
  username = request.POST['username'] 
  password = request.POST['password']
  user = authenticate(username=username, password=password)
  
  if user is not None: 
    if user.is_active:
      auth_login(request, user)
      first_name = request.user.first_name 
      last_name = request.user.last_name
      context = {
              'first_name' : first_name,
              'last_name' : last_name,
            }
      return render(request, 'order_processor/successfullogin.html', context)
      logged_in = True
    else:
      redirect('index')
  else: 
    redirect('index')

def alreadyloggedin(request):
  if request.user.is_authenticated():
    first_name = request.user.first_name
    last_name = request.user.last_name
    return render(request, 'order_processor/alreadyloggedin.html', context)
  else:
    context = {}
    return render(request, 'order_processor/index.html', context)

def driver(request):
  user = request.user  
  if user.groups.filter(name="driver").count():
    driver = Driver.objects.all().filter(user = user)
    order_list = Order.objects.all().filter(status = 'q').filter(driver = driver) 
    context = {
              'order_list' : order_list,
              }
    return render(request, 'order_processor/driver.html', context)
  else:
    HttpResponse("You can't be here silly!")

def order_details(request, order_id):
  order = Order.objects.all().get(id = order_id)    
  username = order.profile.user.username
  item_list = order.items.all()
  cost = str(order.cost)
  establishment_list = order.establishment
  
  context = {
            'order' :order, 
            'username' : username,
            'item_list' : item_list,
            'cost' : cost,
            'establishment_list': establishment_list,
            }
  return render(request, 'order_processor/order_details.html', context)

order_processor/templates/order_processor/alreadyloggedin.html
{% include "order_processor/header.html" %}
  
<p> 
    You're already logged in, {{ first_name }} {{ last_name }}!</ br>
    <form action = "{% url 'index' %}">{% csrf_token %}
      <input type = "submit" Value = "Home" class = "btn btn-default btn-large">
    </form>
</p>
{% include "order_processor/footer.html" %}

order_processor/templates/order_processor/driver.html
{% include "order_processor/header.html" %}
{% if order_list %}
  <ul>
    {% for order in order_list %}
      <li><a href = "{% url 'order_processor:order_details' order.id %}">{{ order.profile.user.username }} | {{ order.city.city }}</a></li>
    {% endfor %}
  </ul>
{% endif %}
{% include "order_processor/footer.html" %}

order_processor/templates/order_processor/footer.html
{% load static from staticfiles %}
<!-- Begin Footer -->

          <div class="mastfoot"> 
            <div class="inner"> 
              <p>Site Coming Soon!</p> 
            </div> 
          </div> <!-- Close msatfoot -->
        </div> <!-- Close cover-container --> 
      </div> <!-- Close site-wrapper-inner -->  
    </div> <!-- Close site-wrapper -->

    <script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-select.js" %}"></script>

    <script type="text/javascript">
        $(window).on('load', function () {
            $('.selectpicker').selectpicker({
                'selectedText': 'cat'
            });
            // $('.selectpicker').selectpicker('hide');
        });
    </script>
  </body>
</html>

<!-- End Footer -->

order_processor/templates/order_processor/header.html
{% load static from staticfiles %}

<!DOCTYPE html>
<!-- Begin Header Test -->

<html>
  <head>
    <meta charset=”utf-8”> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
        
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/cover.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-select.css" %}">
       
    <title> Convenient Delivery </title>      
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
              <h3 class="masthead-brand">Convenient Delivery</h3>
              <ul class = "nav masthead-nav">
                <li class="active" ><a href="/">Home</a></li>
                <li><a href="#">Contact</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'order_processor:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'order_processor:login' %}">Login</a></li>
                <li><a href="{% url 'order_processor:signup'%}">Signup</a></li>
                {% endif %}
              </ul>
          </div> <!-- Close masthead clearfix -->
<!-- End Header -->

order_processor/templates/order_processor/index.html
{% include "order_processor/header.html" %} 

<div class="inner cover">
  <h1 class="cover-heading">Welcome!</h1>
  <p class="lead">Select your Location to begin!</p>
  <form  action="{% url 'order_processor:new_order' %}" method="post"> {% csrf_token %}
    {{ city_select.as_p }}
    <p class="lead">
      <input  type="submit" Value="Begin Order!" class="btn btn-lg btn-default"></input>
    </p>
  </form>  
</div>

{% include "order_processor/footer.html" %}

order_processor/templates/order_processor/login.html
{% include "order_processor/header.html" %}
<h3>Please Login below!</h3>
<form action = "{% url 'order_processor:successfullogin' %}" method = "post"> {% csrf_token %}
  {{  authenticationForm.as_p }}
  <input type = "submit" Value = "Login" class = "btn btn-lg btn-default"></input>
</form>
{% include "order_processor/header.html" %}

order_processor/templates/order_processor/logout.html
{% include "order_processor/header.html" %}
<p>
  You've been logged out {{ user.first_name }} {{ user.last_name }}!</ br>
  <form action = "{% url 'order_processor:index' %}"> {% csrf_token %}
    <input type = "submit" Value = "Home" class = "btn btn-default btn-large">
  </form>
</p>
{% include "order_processor/footer.html" %}

order_processor/templates/order_processor/new_order.html
{% include "order_processor/header.html" %}
  <form action = "{% url 'order_processor:index' %}" method = "post"> {% csrf_token %}
    {{ establishment_selector.as_p }}
    <input type = "submit" value = "Complete Order!" class = "btn btn-lg btn-default"></input>
  </form>
{% include "order_processor/footer.html" %}

order_processor/templates/order_processor/order_details.html
{% include 'order_processor/header.html' %}
  
  <ul>
    <li>ID = {{ order.id }}</li>
      <ul>
        <li>{{ username }}</li>
          {% if item_list %}
            <ul>
              <li>Items</li>
                <ul>
                  {% for item in item_list %}
                    <li>{{ item.name }} | {{ item.establishment.name }}</li>
                  {% endfor %}
                </ul>
            </ul>
          {% endif %}
        <li> {{ cost }}</li>
      </ul>
  </ul>
          
{% include 'order_processor/footer.html' %}

order_processor/templates/order_processor/services.html
{% load static from staticfiles %}

<link rel="stylesheet" href="{% static "css/style.css" %}">



<div id="title_div" class="floated_left">
	<h1> Convenient Delivery </h1> 
</div>
	
<div id="login_div">
	<h2 id="login_header" >Login</h2>
	<form>
		Username: <input class="floated_right padded_10_right" type="text" name = "username"><br>
		Password: <input class="floated_right padded_10_right" type="password" name = "lastname">
	</form>
	<form class="centered">
		<input type="submit" value="Submit">
	</form>
</div>


<div align="center" class = "cleared centered_50%">
	<h2> Please fill out the forms below!</h2>
	Establishment:<select id="Establiment_selector" class="centered_50%">
	<option value="Cumberland_Farms">Cumberland Farms</option>
	</select><br>
	<form class= "centered_50%">
		First name:<input type ="text" name="firstname"><br>
		Last name: <input type="text" name ="lastname"><br>
		<input type="submit" value="Submit">
	</form>
</div>

order_processor/templates/order_processor/signup.html
{% include "order_processor/header.html" %}
<form action = "{% url 'order_processor:successfulsignup' %}" method = "post"> {% csrf_token %}
  {{ signup.as_p }}
  <input type = "submit" Value = "Signup" class = "btn btn-lg btn-default"></input>
</form>
{% include "order_processor/footer.html" %}

order_processor/templates/order_processor/successfullogin.html
{% include "order_processor/header.html" %}
  <p>
    Welcome back {{ first_name }}, {{ last_name }}!</ br>
    Press the button to go back home!</ br>
    <form action = "{% url 'order_processor:index' %}">{% csrf_token %}
      <input type = "submit" Value = "Home" class = "btn btn-default btn-large">
    </form>
  </p>
{% include "order_processor/footer.html" %}
  

order_processor/templates/order_processor/successfulsignup.html
{% include "order_processor/header.html" %}
<p> 
  Welcome {{ first_name }} {{ last_name }}, account successfully created with the following attributes:
  <ul>
    <li>Username: {{ username }}</li>
    <li>Email Adress: {{ email }}</li>
  </ul></ br>
  Press the button below to go back to the main page!
  <form action = "{% url 'order_processor:index' %}">
    <input type="submit" Value ="Home" class= "btn btn-default btn-large">
  </form>
</p>
{% include "order_processor/footer.html" %}